### ISSUE TITLE
We should be able to ignore files or allow opt-in.

### ISSUE THREAD

**Issue by Rio517** [spieker/rspec-apib#1]
I would suggest a global option - `inclusion_policy` that could be `optin` or `all`. If `all` all request specs are included. If `optin` then we could add the `apib: false` option to the `Rspec.describe` options.

**Comment by valii2334** [comment]
@Rio517 From what I understood this option would work like this: if inclusion_policy is :all we bypass apib: false and we include all request specs but if inclusion_policy is :optin we do what we do now ( we take into consideration apib: false ).

**Comment by spieker** [comment]
Closed by https://github.com/spieker/rspec-apib/pull/11
